import type { User, Claim, Notification, Trigger, Payout, AnalyticsData, Plan } from '../types';

export const PLANS: Plan[] = [
  {
    id: 'basic',
    name: 'Basic Shield',
    price: 99,
    coverage: 500,
    features: [
      'Weather disruption coverage',
      'Up to ₹500/day payout',
      'SMS alerts',
      'Standard claim processing (24h)',
      '3 claims per month',
    ],
  },
  {
    id: 'plus',
    name: 'Plus Shield',
    price: 199,
    coverage: 1200,
    popular: true,
    features: [
      'Weather + AQI + Curfew coverage',
      'Up to ₹1,200/day payout',
      'App + SMS alerts',
      'Priority claim processing (4h)',
      '10 claims per month',
      'Platform outage coverage',
      'Fraud protection guarantee',
    ],
  },
  {
    id: 'pro',
    name: 'Pro Shield',
    price: 349,
    coverage: 2500,
    features: [
      'All disruption types covered',
      'Up to ₹2,500/day payout',
      'Real-time AI alerts',
      'Instant auto-payout (<15 min)',
      'Unlimited claims',
      'Dedicated support agent',
      'ZARS risk score boost',
      'Family accident cover',
    ],
  },
];

export const MOCK_WORKERS: User[] = [
  {
    id: 'w001',
    name: 'Arjun Sharma',
    email: 'arjun@worker.com',
    role: 'worker',
    phone: '+91 98765 43210',
    city: 'Mumbai',
    zone: 'Andheri West',
    platform: 'zomato',
    trustScore: 87,
    zarsScore: 72,
    plan: 'plus',
    joinedAt: '2024-03-15',
    earnings: { today: 820, week: 5240, month: 21800 },
  },
  {
    id: 'w002',
    name: 'Priya Menon',
    email: 'priya@worker.com',
    role: 'worker',
    phone: '+91 87654 32109',
    city: 'Bangalore',
    zone: 'Koramangala',
    platform: 'swiggy',
    trustScore: 94,
    zarsScore: 88,
    plan: 'pro',
    joinedAt: '2024-01-08',
    earnings: { today: 1340, week: 7890, month: 31200 },
  },
  {
    id: 'w003',
    name: 'Ravi Kumar',
    email: 'ravi@worker.com',
    role: 'worker',
    phone: '+91 76543 21098',
    city: 'Delhi',
    zone: 'Connaught Place',
    platform: 'both',
    trustScore: 61,
    zarsScore: 45,
    plan: 'basic',
    joinedAt: '2024-06-22',
    earnings: { today: 420, week: 2980, month: 12500 },
  },
  {
    id: 'w004',
    name: 'Sneha Patel',
    email: 'sneha@worker.com',
    role: 'worker',
    phone: '+91 65432 10987',
    city: 'Ahmedabad',
    zone: 'SG Highway',
    platform: 'zomato',
    trustScore: 79,
    zarsScore: 65,
    plan: 'plus',
    joinedAt: '2024-04-11',
    earnings: { today: 680, week: 4320, month: 18700 },
  },
  {
    id: 'w005',
    name: 'Mohammed Ali',
    email: 'mali@worker.com',
    role: 'worker',
    phone: '+91 54321 09876',
    city: 'Hyderabad',
    zone: 'Banjara Hills',
    platform: 'swiggy',
    trustScore: 92,
    zarsScore: 81,
    plan: 'pro',
    joinedAt: '2023-11-30',
    earnings: { today: 1180, week: 6750, month: 28900 },
  },
];

export const MOCK_ADMIN: User = {
  id: 'a001',
  name: 'Kavya Reddy',
  email: 'admin@shieldgig.in',
  role: 'admin',
  phone: '+91 99887 76655',
  city: 'Bangalore',
  zone: 'HSR Layout',
  platform: 'both',
  trustScore: 100,
  zarsScore: 100,
  plan: 'pro',
  joinedAt: '2023-09-01',
  earnings: { today: 0, week: 0, month: 0 },
};

export const MOCK_CLAIMS: Claim[] = [
  {
    id: 'clm001',
    workerId: 'w001',
    workerName: 'Arjun Sharma',
    type: 'weather',
    status: 'approved',
    amount: 1200,
    requestedAt: '2025-04-01T10:30:00Z',
    resolvedAt: '2025-04-01T14:22:00Z',
    fraudScore: 12,
    fraudFlags: [],
    city: 'Mumbai',
    zone: 'Andheri West',
    description: 'Heavy rainfall (RedAlert) - Unable to deliver for 6 hours',
  },
  {
    id: 'clm002',
    workerId: 'w002',
    workerName: 'Priya Menon',
    type: 'aqi',
    status: 'approved',
    amount: 2500,
    requestedAt: '2025-03-28T08:00:00Z',
    resolvedAt: '2025-03-28T08:42:00Z',
    fraudScore: 5,
    fraudFlags: [],
    city: 'Bangalore',
    zone: 'Koramangala',
    description: 'AQI exceeded 400 (Hazardous) - Health safety auto-trigger',
  },
  {
    id: 'clm003',
    workerId: 'w003',
    workerName: 'Ravi Kumar',
    type: 'platform_outage',
    status: 'under_review',
    amount: 500,
    requestedAt: '2025-04-02T15:45:00Z',
    fraudScore: 67,
    fraudFlags: [
      { type: 'location_mismatch', severity: 'high', description: 'GPS location does not match claimed delivery zone' },
      { type: 'suspicious_timing', severity: 'medium', description: 'Claim filed 4 hours after reported outage ended' },
    ],
    city: 'Delhi',
    zone: 'Connaught Place',
    description: 'Zomato platform down for 3 hours',
  },
  {
    id: 'clm004',
    workerId: 'w004',
    workerName: 'Sneha Patel',
    type: 'weather',
    status: 'rejected',
    amount: 1200,
    requestedAt: '2025-03-25T12:00:00Z',
    resolvedAt: '2025-03-25T18:30:00Z',
    fraudScore: 89,
    fraudFlags: [
      { type: 'repeated_claim', severity: 'high', description: '5 identical claims filed within 7 days' },
      { type: 'velocity_check', severity: 'high', description: 'Claims frequency exceeds normal pattern by 340%' },
      { type: 'device_anomaly', severity: 'medium', description: 'Multiple devices detected for same account' },
    ],
    city: 'Ahmedabad',
    zone: 'SG Highway',
    description: 'Claim rejected due to high fraud score',
  },
  {
    id: 'clm005',
    workerId: 'w005',
    workerName: 'Mohammed Ali',
    type: 'curfew',
    status: 'approved',
    amount: 2500,
    requestedAt: '2025-04-03T06:00:00Z',
    resolvedAt: '2025-04-03T06:18:00Z',
    fraudScore: 8,
    fraudFlags: [],
    city: 'Hyderabad',
    zone: 'Banjara Hills',
    description: 'Section 144 imposed - No delivery possible 6AM-10PM',
  },
  {
    id: 'clm006',
    workerId: 'w001',
    workerName: 'Arjun Sharma',
    type: 'aqi',
    status: 'pending',
    amount: 1200,
    requestedAt: '2025-04-03T16:00:00Z',
    fraudScore: 21,
    fraudFlags: [
      { type: 'suspicious_timing', severity: 'low', description: 'Claim filed during peak AQI hours' },
    ],
    city: 'Mumbai',
    zone: 'Andheri West',
    description: 'AQI 380 - Elevated pollution levels disrupting operations',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n001',
    title: '🌧️ Weather Alert — Mumbai',
    message: 'Red Alert issued for Andheri West. Auto-payout of ₹1,200 triggered.',
    type: 'payout',
    read: false,
    createdAt: '2025-04-03T10:32:00Z',
  },
  {
    id: 'n002',
    title: '✅ Claim Approved',
    message: 'Your claim #CLM001 has been approved. ₹1,200 will be credited in 2-4 hours.',
    type: 'approval',
    read: false,
    createdAt: '2025-04-03T09:15:00Z',
  },
  {
    id: 'n003',
    title: '⚠️ AQI Warning — Your Zone',
    message: 'AQI in Andheri West has crossed 300 (Very Poor). Consider limiting outdoor exposure.',
    type: 'alert',
    read: true,
    createdAt: '2025-04-02T14:20:00Z',
  },
  {
    id: 'n004',
    title: '💳 Payout Credited',
    message: '₹1,200 has been successfully credited to your UPI ID arjun@upi',
    type: 'payout',
    read: true,
    createdAt: '2025-04-01T16:45:00Z',
  },
  {
    id: 'n005',
    title: '📋 Plan Renewal',
    message: 'Your Plus Shield plan renews in 7 days. Ensure auto-renewal is enabled.',
    type: 'info',
    read: true,
    createdAt: '2025-03-28T08:00:00Z',
  },
];

export const MOCK_TRIGGERS: Trigger[] = [
  {
    id: 't001',
    type: 'weather',
    city: 'Mumbai',
    zone: 'Andheri West',
    severity: 'critical',
    status: 'active',
    affectedWorkers: 247,
    triggeredAt: '2025-04-03T09:00:00Z',
    autoPayoutEnabled: true,
    payoutAmount: 1200,
    description: 'IMD Red Alert — Extremely heavy rainfall expected. Winds 80kmph.',
  },
  {
    id: 't002',
    type: 'aqi',
    city: 'Delhi',
    zone: 'All Zones',
    severity: 'high',
    status: 'active',
    affectedWorkers: 1843,
    triggeredAt: '2025-04-03T07:30:00Z',
    autoPayoutEnabled: true,
    payoutAmount: 500,
    description: 'AQI 412 — Hazardous air quality. GRAP Stage IV restrictions in effect.',
  },
  {
    id: 't003',
    type: 'platform_outage',
    city: 'Bangalore',
    zone: 'All Zones',
    severity: 'medium',
    status: 'resolved',
    affectedWorkers: 892,
    triggeredAt: '2025-04-02T14:00:00Z',
    resolvedAt: '2025-04-02T17:15:00Z',
    autoPayoutEnabled: false,
    payoutAmount: 800,
    description: 'Swiggy platform outage — App unresponsive for 3h 15m',
  },
  {
    id: 't004',
    type: 'curfew',
    city: 'Hyderabad',
    zone: 'Old City',
    severity: 'critical',
    status: 'monitoring',
    affectedWorkers: 312,
    triggeredAt: '2025-04-01T20:00:00Z',
    autoPayoutEnabled: true,
    payoutAmount: 2500,
    description: 'Section 144 imposed due to communal tension. All movement restricted.',
  },
];

export const MOCK_PAYOUTS: Payout[] = [
  {
    id: 'pay001',
    workerId: 'w001',
    workerName: 'Arjun Sharma',
    amount: 1200,
    status: 'completed',
    method: 'upi',
    triggeredBy: 'Weather Auto-Trigger',
    createdAt: '2025-04-03T10:32:00Z',
    completedAt: '2025-04-03T10:47:00Z',
  },
  {
    id: 'pay002',
    workerId: 'w002',
    workerName: 'Priya Menon',
    amount: 2500,
    status: 'completed',
    method: 'bank',
    triggeredBy: 'AQI Auto-Trigger',
    createdAt: '2025-04-03T08:00:00Z',
    completedAt: '2025-04-03T08:18:00Z',
  },
  {
    id: 'pay003',
    workerId: 'w005',
    workerName: 'Mohammed Ali',
    amount: 2500,
    status: 'processing',
    method: 'upi',
    triggeredBy: 'Curfew Auto-Trigger',
    createdAt: '2025-04-03T06:05:00Z',
  },
  {
    id: 'pay004',
    workerId: 'w004',
    workerName: 'Sneha Patel',
    amount: 1200,
    status: 'failed',
    method: 'upi',
    triggeredBy: 'Manual Claim',
    createdAt: '2025-03-25T12:30:00Z',
  },
  {
    id: 'pay005',
    workerId: 'w003',
    workerName: 'Ravi Kumar',
    amount: 500,
    status: 'pending',
    method: 'wallet',
    triggeredBy: 'Platform Outage',
    createdAt: '2025-04-02T15:50:00Z',
  },
];

export const ANALYTICS_DATA: AnalyticsData[] = [
  { date: 'Mar 28', claims: 34, payouts: 28, revenue: 42000, activeWorkers: 1820 },
  { date: 'Mar 29', claims: 41, payouts: 35, revenue: 58000, activeWorkers: 1930 },
  { date: 'Mar 30', claims: 28, payouts: 22, revenue: 31000, activeWorkers: 1780 },
  { date: 'Mar 31', claims: 67, payouts: 58, revenue: 89000, activeWorkers: 2100 },
  { date: 'Apr 01', claims: 92, payouts: 81, revenue: 124000, activeWorkers: 2340 },
  { date: 'Apr 02', claims: 55, payouts: 48, revenue: 76000, activeWorkers: 2180 },
  { date: 'Apr 03', claims: 118, payouts: 94, revenue: 158000, activeWorkers: 2560 },
];
